version: 2

# Check npm dependencies (frontend & backend)
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
    # Enable auto-merge for patch and minor updates only
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major"]
    auto-merge: true

# Check GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
